type = "javascript"
accountid = "6149cdb975d03c73edb1ba984159e74d"
zoneid = "2ff6392051f54a50c21ef3a8929f807d"
name = "ipv6-tools"

[env.staging]
name = "ipv6-tools-staging"
route = "staging.ipv6.tools/*"

[env.production]
name = "ipv6-tools-prod"
route = "ipv6.tools/*"
